---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/digirise/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH