<?php

/*
|--------------------------------------------------------------------------
| Digirisers Catalog
|--------------------------------------------------------------------------
|
| Single source of truth for service categories, prices, descriptions, and
| product detail copy. Used by:
|   - resources/views/services.blade.php          (services index)
|   - resources/views/services-category.blade.php (sub-page per category)
|   - resources/views/shop.blade.php              (shop catalog)
|   - resources/views/shop-detail.blade.php       (single product page)
|   - resources/views/partials/header.blade.php   (mega menu)
|   - resources/views/home.blade.php              (homepage previews)
|
| Cycle values: 'project' | 'mo' | 'week' | 'per Zap' | 'per script' | 'per asset'
|
*/

return [

    'categories' => [

        'websites' => [
            'id'      => 'websites',
            'order'   => 1,
            'eyebrow' => 'Build',
            'title'   => 'Websites & Funnels',
            'tagline' => 'Sites that convert. Funnels that compound.',
            'icon'    => 'monitor',
            'hero'    => 'Custom-designed sites and sales funnels — built to look premium, load fast, and turn visitors into pipeline.',
            'blurb'   => 'WordPress, custom-coded sites, e-commerce, and full sales funnels — engineered to convert.',
            'process' => [
                ['Discovery', 'Goals, audience, and content map'],
                ['Design',    'High-fidelity mockups in your brand'],
                ['Build',     'WordPress, custom, or funnel platform'],
                ['Launch',    'QA, tracking, and post-launch tuning'],
            ],
            'items' => [
                [
                    'slug'  => 'wp-portfolio',
                    'name'  => 'WordPress Portfolio Site',
                    'price' => 300,
                    'cycle' => 'project',
                    'blurb' => 'A clean, fast portfolio site built on WordPress with a premium template.',
                    'detail'=> "Perfect for solopreneurs, freelancers, and creators. We pick a premium template, customize it to your brand, set up your pages, and ship — all in under a week. Built on a battle-tested WordPress stack with security and speed dialed in from day one.",
                    'includes' => [
                        'Premium WordPress template',
                        'Up to 5 pages, brand-customized',
                        'Mobile-responsive QA',
                        'Contact form + email forwarding',
                        'Basic on-page SEO (titles + meta)',
                        '14-day post-launch support',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Solopreneurs, creators, and small portfolios.',
                ],
                [
                    'slug'  => 'wp-business',
                    'name'  => 'WordPress Business Site (5–7 pages, Elementor)',
                    'price' => 500,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A professional business site built with Elementor — content-managed and easy to update.',
                    'detail'=> "A high-quality WordPress business site with 5–7 pages, custom-built in Elementor. Looks premium, loads fast, and gives your team full control to edit content without ever touching code. Built with conversion in mind on every page.",
                    'includes' => [
                        '5–7 fully designed pages',
                        'Custom Elementor build (no themes)',
                        'Mobile + tablet responsive',
                        'Lead capture + CRM forwarding',
                        'On-page SEO foundations',
                        'CMS training video',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Service businesses, agencies, and B2B teams.',
                ],
                [
                    'slug'  => 'custom-site',
                    'name'  => 'Custom Designed Website / Sales Funnel',
                    'price' => 800,
                    'cycle' => 'project',
                    'blurb' => 'A bespoke, conversion-focused site or funnel — designed and built from scratch.',
                    'detail'=> "A fully custom website or sales funnel — designed in Figma, hand-coded or built in Webflow/Elementor, and engineered for conversion. Every section is intentional. Every layout is tested. Every line of copy is positioned to move someone closer to becoming a customer.",
                    'includes' => [
                        'Custom Figma design (3 rounds)',
                        'Up to 8 pages or 5-step funnel',
                        'Conversion-optimized layouts',
                        'Fast-loading (Core Web Vitals pass)',
                        'Lead capture + analytics',
                        '30-day post-launch support',
                    ],
                    'timeline' => '14–21 business days',
                    'idealFor' => 'Brands that need a site that performs, not just exists.',
                ],
                [
                    'slug'  => 'custom-site-integrations',
                    'name'  => 'Custom Site / Funnel + Integrations',
                    'price' => 1000,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'Custom-designed site + payments, CRM, ManyChat, and full lead routing.',
                    'detail'=> "Everything in our Custom Designed Website + payment processing (Stripe / PayPal / etc.), ManyChat or AI chat, GoHighLevel / DisputeFox / Zoho / Credit Repair Cloud CRM hookup, and full webhook lead routing. The end-to-end revenue stack on launch day.",
                    'includes' => [
                        'Custom Figma design + build',
                        'Payment processor integration',
                        'CRM integration (GHL / Zoho / etc.)',
                        'ManyChat or AI chat setup',
                        'Webhook + lead routing',
                        'Full QA + post-launch support',
                    ],
                    'timeline' => '21–28 business days',
                    'idealFor' => 'Brands running real sales pipelines through their site.',
                ],
                [
                    'slug'  => 'ecommerce',
                    'name'  => 'E-commerce Store (up to 25 products)',
                    'price' => 1200,
                    'cycle' => 'project',
                    'blurb' => 'Conversion-focused e-commerce store — Shopify, Woo, or custom — up to 25 products.',
                    'detail'=> "A premium e-commerce store designed to convert: clean product pages, fast cart, optimized checkout, abandoned-cart flows, and conversion-tested layouts. Up to 25 products migrated or created. Pick your platform — Shopify, WooCommerce, or custom.",
                    'includes' => [
                        'Shopify, WooCommerce, or custom',
                        'Up to 25 products configured',
                        'Optimized PDP + cart + checkout',
                        'Abandoned-cart email flows',
                        'Payments + shipping setup',
                        'Analytics + tracking pixels',
                    ],
                    'timeline' => '21–28 business days',
                    'idealFor' => 'DTC and product brands launching or relaunching.',
                ],
                [
                    'slug'  => 'landing-page',
                    'name'  => 'Landing Page (single, conversion-optimized)',
                    'price' => 250,
                    'cycle' => 'project',
                    'blurb' => 'A single high-converting landing page — perfect for ads, launches, and offers.',
                    'detail'=> "A focused, conversion-optimized landing page built to support a single offer or campaign. Includes a copy framework, custom design, build, and analytics. Built fast — typically live in a week — so you can start running traffic immediately.",
                    'includes' => [
                        'Copy + offer framework',
                        'Conversion-optimized layout',
                        'Mobile-first design',
                        'Pixel + analytics installation',
                        'Lead form / payment / booking',
                        'A/B test variant (optional)',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Anyone running paid ads or launching an offer.',
                ],
                [
                    'slug'  => 'funnel-build',
                    'name'  => 'Funnel Build (3-step: opt-in → sales → upsell)',
                    'price' => 600,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A complete 3-step sales funnel — opt-in, sales, upsell — wired to your CRM.',
                    'detail'=> "A complete 3-step funnel: opt-in / lead capture → sales page → upsell / thank-you. CRM-wired, payment-ready, and built around copy and design that converts. The whole flow ships as one production-ready system.",
                    'includes' => [
                        '3 fully-designed funnel pages',
                        'Opt-in + email automation',
                        'Sales page with copy framework',
                        'Upsell or order bump',
                        'CRM + payment integration',
                        'Conversion tracking installed',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Coaches, course creators, and digital products.',
                ],
                [
                    'slug'  => 'website-revamp',
                    'name'  => 'Website Revamp / Redesign',
                    'price' => 650,
                    'cycle' => 'project',
                    'blurb' => 'A full redesign of your existing site — modernized, optimized, and ready to convert.',
                    'detail'=> "We audit your current site, redesign every page for conversion, and rebuild on the same platform (or migrate to a better one). Includes brand alignment, copy refresh, and Core Web Vitals tuning so the new site is faster and clearer than the old one.",
                    'includes' => [
                        'Site audit + heatmap review',
                        'Full design refresh',
                        'Copy alignment + clarity pass',
                        'Core Web Vitals optimization',
                        'SEO redirect map',
                        '14-day post-launch support',
                    ],
                    'timeline' => '14–21 business days',
                    'idealFor' => 'Sites that look dated or aren\'t converting.',
                ],
                [
                    'slug'  => 'cro-audit',
                    'name'  => 'CRO Audit + Implementation',
                    'price' => 400,
                    'cycle' => 'project',
                    'blurb' => 'Conversion audit + a focused round of changes to lift your conversion rate.',
                    'detail'=> "A 50+ point CRO audit followed by a focused implementation sprint. We diagnose, prioritize, and ship the highest-leverage fixes. Typical lift: 15–40% on the audited pages, with a clear before/after benchmark report.",
                    'includes' => [
                        '50+ point CRO audit report',
                        'Heatmap + session review',
                        'Top-10 prioritized fix list',
                        'Implementation of top 5 fixes',
                        'Before/after benchmark report',
                        'Optional A/B testing add-on',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Sites with traffic but underwhelming conversion.',
                ],
            ],
        ],

        'ai' => [
            'id'      => 'ai',
            'order'   => 2,
            'eyebrow' => 'Automate',
            'title'   => 'AI Infrastructure & Agentic Systems',
            'tagline' => 'Hire AI. Compound your team.',
            'icon'    => 'brain',
            'hero'    => 'AI agents that handle support, sales, admin, and operations — wired into your CRM, calendar, and inbox 24/7.',
            'blurb'   => 'AI agents and infrastructure that handle support, sales, admin, and data work without burning out.',
            'process' => [
                ['Scope',  'Define agent role and KPIs'],
                ['Train',  'Knowledge base + tool access'],
                ['Deploy', 'Wire into CRM, inbox, and calendar'],
                ['Tune',   'Continuous prompt + behavior tuning'],
            ],
            'items' => [
                [
                    'slug'  => 'ai-chatbot',
                    'name'  => 'AI Web Chatbot / Knowledge Base',
                    'price' => 400,
                    'cycle' => 'project',
                    'blurb' => 'A branded AI chat for your site — trained on your docs and FAQs.',
                    'detail'=> "A custom AI chatbot embedded on your site: trained on your docs, website, and FAQs using retrieval-augmented generation. Handles support questions, captures leads, and escalates to a human when it's out of its depth.",
                    'includes' => [
                        'Custom AI chatbot',
                        'RAG over your knowledge base',
                        'Branded UI widget',
                        'Lead capture + escalation',
                        'Conversation logging',
                        'Monthly knowledge refresh option',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Anyone with frequent support questions or a docs site.',
                ],
                [
                    'slug'  => 'ai-support-agent',
                    'name'  => 'AI Customer Support Agent',
                    'price' => 600,
                    'cycle' => 'project',
                    'blurb' => 'A 24/7 AI support agent that resolves tickets and escalates the rest.',
                    'detail'=> "A customer-support AI that handles 60–80% of incoming tickets autonomously: answers FAQs, processes refunds within rules you set, escalates complex cases, and updates your CRM. Lives across chat and email.",
                    'includes' => [
                        'Custom AI support agent',
                        'Tool access (CRM, refunds, etc.)',
                        'Escalation rules',
                        'Multi-channel (chat / email)',
                        'Performance dashboard',
                        '30-day tuning support',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Brands drowning in support tickets.',
                ],
                [
                    'slug'  => 'ai-sales-agent',
                    'name'  => 'AI Sales & Appointment Setter',
                    'price' => 700,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'An AI SDR that qualifies leads and books meetings on autopilot.',
                    'detail'=> "An AI sales agent that qualifies inbound leads, answers their questions, handles objections, and books meetings on your calendar — across SMS, email, or chat. Wired into your CRM so every interaction is logged.",
                    'includes' => [
                        'Custom AI sales agent',
                        'Qualification + objection handling',
                        'Calendar integration',
                        'CRM sync',
                        'Multi-channel (SMS / email / chat)',
                        '30-day tuning support',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Sales teams with steady inbound flow.',
                ],
                [
                    'slug'  => 'ai-admin-assistant',
                    'name'  => 'AI Admin / Task Assistant',
                    'price' => 500,
                    'cycle' => 'project',
                    'blurb' => 'An AI admin that handles inbox, calendar, and recurring tasks.',
                    'detail'=> "An AI admin assistant for founders and execs: triages your inbox, manages your calendar, drafts replies in your voice, summarizes meetings, and handles recurring ops tasks. Like hiring an EA who never sleeps.",
                    'includes' => [
                        'Custom AI admin agent',
                        'Inbox triage + drafting',
                        'Calendar management',
                        'Meeting summarization',
                        'Task automation',
                        '30-day tuning support',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Founders, execs, and ops leads.',
                ],
                [
                    'slug'  => 'ai-data-bot',
                    'name'  => 'AI Data Processing Bot',
                    'price' => 450,
                    'cycle' => 'project',
                    'blurb' => 'Automate data extraction, enrichment, and cleaning at scale.',
                    'detail'=> "An AI bot that handles data work: extract structured data from documents (OCR + LLM), enrich CRM records, clean spreadsheets, and run recurring data tasks without burning a team member's day.",
                    'includes' => [
                        'Custom data processing bot',
                        'Document extraction (OCR + LLM)',
                        'CRM enrichment',
                        'Recurring task scheduling',
                        'Error handling + alerts',
                        'Documentation',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Teams with manual data entry pain.',
                ],
                [
                    'slug'  => 'predictive-automation',
                    'name'  => 'Predictive Automation & Personalization',
                    'price' => 800,
                    'cycle' => 'project',
                    'blurb' => 'ML-driven personalization across email, SMS, and your site.',
                    'detail'=> "A predictive personalization layer: ML models that predict customer behavior — churn, LTV, next-purchase — and trigger personalized email, SMS, and on-site experiences in real time.",
                    'includes' => [
                        'Behavior prediction models',
                        'Personalization rules engine',
                        'Email + SMS + on-site triggers',
                        'A/B testing infrastructure',
                        'Performance dashboards',
                        'Documentation',
                    ],
                    'timeline' => '14–21 business days',
                    'idealFor' => 'DTC, SaaS, and subscription brands.',
                ],
                [
                    'slug'  => 'prompt-engineering',
                    'name'  => 'Prompt Engineering Package',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'Production-grade prompts — designed, tested, and version-controlled.',
                    'detail'=> "A focused prompt-engineering engagement: 5–10 production prompts designed, tested, and version-controlled. With test cases, evals, and a tuning guide so your team can iterate after we hand off.",
                    'includes' => [
                        '5–10 production prompts',
                        'Test cases + evals',
                        'Version control + docs',
                        'Tuning guide',
                        'Cost optimization tips',
                        '14-day follow-up support',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'Teams using LLMs in production.',
                ],
                [
                    'slug'  => 'workflow-orchestration',
                    'name'  => 'AI Workflow Orchestration (n8n / custom)',
                    'price' => 650,
                    'cycle' => 'project',
                    'blurb' => 'Multi-agent orchestration with tools, guardrails, and observability.',
                    'detail'=> "Custom multi-agent orchestration on n8n or hand-coded: multi-step agent flows with tool access, guardrails, retries, and full observability. The plumbing your AI agents actually need to run reliably.",
                    'includes' => [
                        'n8n / custom orchestration',
                        'Multi-step agent flows',
                        'Tool access + guardrails',
                        'Retries + error handling',
                        'Observability + logging',
                        'Documentation',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Operationally complex AI workflows.',
                ],
                [
                    'slug'  => 'full-ai-employee',
                    'name'  => 'Full AI Employee Deployment',
                    'price' => 1200,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A full AI employee — owns a function end-to-end across your tools.',
                    'detail'=> "A turnkey AI employee that owns a real business function (sales, support, ops) end-to-end: trained on your business, wired into your tools, with a manager dashboard so you can supervise it like any team member.",
                    'includes' => [
                        'Full role definition + training',
                        'Multi-tool access (CRM, inbox, etc.)',
                        'Custom dashboard + reporting',
                        'Escalation + handoff rules',
                        '60-day tuning support',
                        'Replacement guarantee',
                    ],
                    'timeline' => '21–28 business days',
                    'idealFor' => 'Teams replacing or augmenting a hire.',
                ],
            ],
        ],

        'seo' => [
            'id'      => 'seo',
            'order'   => 3,
            'eyebrow' => 'Grow',
            'title'   => 'SEO',
            'tagline' => 'Found in Google. Cited in ChatGPT.',
            'icon'    => 'search',
            'hero'    => 'Get found where buyers actually search — Google, Maps, AI search, and the platforms specific to your category.',
            'blurb'   => 'Technical, on-page, local, and AI search optimization that compounds month over month.',
            'process' => [
                ['Audit',      'Site, content, and SERP teardown'],
                ['Foundation', 'Technical fixes + content map'],
                ['Compound',   'Monthly content + authority building'],
                ['Report',     'Rankings, traffic, and revenue impact'],
            ],
            'items' => [
                [
                    'slug'  => 'local-seo',
                    'name'  => 'Local SEO Setup (GBP + citations)',
                    'price' => 300,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'Get found in Google Maps with a fully-optimized profile and clean citations.',
                    'detail'=> "A complete local SEO foundation: Google Business Profile setup and optimization, top-30 citation submissions, NAP consistency cleanup, review-request automation, and local schema markup. The fastest path to ranking in Maps for local service businesses.",
                    'includes' => [
                        'Google Business Profile setup',
                        'Top 30 citation submissions',
                        'NAP consistency audit',
                        'Review request automation',
                        'Local schema markup',
                        'Local keyword research',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Local service businesses (med spas, contractors, lawyers).',
                ],
                [
                    'slug'  => 'technical-seo',
                    'name'  => 'Technical SEO Audit',
                    'price' => 250,
                    'cycle' => 'project',
                    'blurb' => 'Find every technical issue holding your rankings back.',
                    'detail'=> "A comprehensive technical SEO audit: crawlability, indexation, schema, Core Web Vitals, internal linking, and on-page issues. Comes with a prioritized fix list and a Loom walkthrough so you know exactly what to ship next.",
                    'includes' => [
                        'Crawl + index audit',
                        'Core Web Vitals review',
                        'Schema markup review',
                        'Internal linking analysis',
                        'Prioritized fix list',
                        'Loom walkthrough',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Sites with 50+ pages or stalled organic growth.',
                ],
                [
                    'slug'  => 'on-page-seo',
                    'name'  => 'On-Page SEO (per 10 pages)',
                    'price' => 300,
                    'cycle' => 'project',
                    'blurb' => 'Optimize 10 priority pages — titles, headings, content, and internal links.',
                    'detail'=> "Page-by-page on-page SEO across 10 priority pages. We rewrite titles, optimize headings, expand content where needed, fix internal linking, and add schema. With a clear before/after report so you can see the lift.",
                    'includes' => [
                        '10 pages fully optimized',
                        'Titles + meta + headings',
                        'Content gap analysis',
                        'Internal linking improvements',
                        'Schema markup',
                        'Before/after report',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Sites with content but weak rankings.',
                ],
                [
                    'slug'  => 'monthly-seo',
                    'name'  => 'Monthly SEO Retainer',
                    'price' => 450,
                    'cycle' => 'mo',
                    'tag'   => 'popular',
                    'blurb' => 'Ongoing SEO — content, links, and optimization that compounds.',
                    'detail'=> "A focused monthly SEO retainer combining new content, link building, technical maintenance, and reporting. Built to compound traffic over 6–12 months — the realistic SEO timeline anyone honest will quote you.",
                    'includes' => [
                        '2 SEO articles per month',
                        'Ongoing on-page optimization',
                        '5 quality backlinks / month',
                        'Technical maintenance',
                        'Monthly performance report',
                        'Quarterly strategy review',
                    ],
                    'timeline' => 'Ongoing monthly retainer',
                    'idealFor' => 'Brands serious about organic growth.',
                ],
                [
                    'slug'  => 'programmatic-seo',
                    'name'  => 'Programmatic SEO Build (template + 500 pages)',
                    'price' => 900,
                    'cycle' => 'project',
                    'blurb' => 'Spin up 500+ targeted pages from a template — programmatic SEO at scale.',
                    'detail'=> "Build a programmatic SEO system: data source + page template + 500 generated pages targeting long-tail queries. Indexable, fast, and SERP-ready. The same playbook used by every directory and marketplace that ranks for 50,000 keywords.",
                    'includes' => [
                        'Keyword + data research',
                        'Page template (1–3 variants)',
                        '500 pages generated + deployed',
                        'Sitemap + indexing strategy',
                        'Schema + internal linking',
                        '30-day indexation monitoring',
                    ],
                    'timeline' => '14–21 business days',
                    'idealFor' => 'Marketplaces, SaaS, directories, and travel.',
                ],
                [
                    'slug'  => 'aeo-optimization',
                    'name'  => 'AI Search Optimization (ChatGPT / Gemini / Grok)',
                    'price' => 350,
                    'cycle' => 'project',
                    'tag'   => 'new',
                    'blurb' => 'Get cited inside ChatGPT, Gemini, Perplexity, and Grok — the new search.',
                    'detail'=> "AEO (Answer Engine Optimization) is the new SEO. We restructure your content, add schema, and seed authority across the surfaces ChatGPT, Gemini, Perplexity, and Grok actually pull from. A real strategy for the post-Google search world.",
                    'includes' => [
                        'AEO content audit',
                        'Answer-first restructuring',
                        'Schema + entity markup',
                        'Source authority seeding',
                        'Citation tracking setup',
                        'AI search visibility report',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Brands worried about losing traffic to AI search.',
                ],
                [
                    'slug'  => 'backlink-outreach',
                    'name'  => 'Backlink Outreach',
                    'price' => 250,
                    'cycle' => 'mo',
                    'blurb' => 'White-hat backlink building — real placements on real sites.',
                    'detail'=> "Manual, white-hat backlink outreach: 5–8 quality placements per month on relevant sites with real authority. No PBNs, no paid links, no junk. The kind of links that actually move rankings without putting you at risk.",
                    'includes' => [
                        '5–8 placements / month',
                        'Manual prospecting + outreach',
                        'Editorial guest posts',
                        'Niche + relevant only',
                        'DR 30+ targets',
                        'Monthly placement report',
                    ],
                    'timeline' => 'Ongoing monthly retainer',
                    'idealFor' => 'Sites that need authority to rank.',
                ],
                [
                    'slug'  => 'keyword-research',
                    'name'  => 'Keyword Research & Strategy Doc',
                    'price' => 150,
                    'cycle' => 'project',
                    'blurb' => 'A complete keyword strategy — clusters, intent, priority, and content plan.',
                    'detail'=> "A standalone deliverable: full keyword research with topic clusters, search intent classification, priority scoring, and a 6-month content plan you can hand to any writer or content team.",
                    'includes' => [
                        '300+ keywords researched',
                        'Topic clusters mapped',
                        'Search intent classified',
                        '6-month content calendar',
                        'Competitor content gaps',
                        'Loom walkthrough',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'Brands planning content but missing strategy.',
                ],
            ],
        ],

        'paid-ads' => [
            'id'      => 'paid-ads',
            'order'   => 4,
            'eyebrow' => 'Grow',
            'title'   => 'Paid Advertising',
            'tagline' => 'Profitable ads, dialed in fast.',
            'icon'    => 'target',
            'hero'    => 'Stop guessing where to spend. We build, run, and optimize ad campaigns that print pipeline — across Google, Meta, TikTok, X, and streaming.',
            'blurb'   => 'Profitable paid campaigns built and managed end-to-end across Google, Meta, TikTok, and streaming.',
            'process' => [
                ['Audit',  'Account, creative, and tracking review'],
                ['Build',  'Structure, audiences, and pixel hardening'],
                ['Launch', 'Tight creative testing & budget pacing'],
                ['Scale',  'Weekly optimization with full-funnel reporting'],
            ],
            'items' => [
                [
                    'slug'  => 'ads-setup',
                    'name'  => 'Ads Setup (per platform)',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'Account hardening, pixel setup, audiences, and your first set of campaigns on one platform.',
                    'detail'=> "We build your ad account from the ground up — pixel and Conversions API installation, audience seeds, naming conventions, account hygiene, billing safety, and launch-ready campaigns. Pick one platform: Google, Meta, TikTok, X, or LinkedIn.",
                    'includes' => [
                        'Pixel + Conversions API installation',
                        'Custom + lookalike audience seeds',
                        'Account naming conventions',
                        'Initial campaign structure',
                        'Conversion goal mapping',
                        '14-day post-launch QA',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Brands launching on a new ad platform or fixing a messy account.',
                ],
                [
                    'slug'  => 'ads-management',
                    'name'  => 'Ads Management (per platform / week)',
                    'price' => 125,
                    'cycle' => 'week',
                    'tag'   => 'popular',
                    'blurb' => 'Hands-on weekly ad management — bids, creative testing, budget pacing, and reports.',
                    'detail'=> "Active human management — not 'set and forget'. We manage your bids, creative rotation, audience refreshes, and budgets, with weekly performance reviews and clear reporting. Per platform.",
                    'includes' => [
                        'Weekly bid + budget pacing review',
                        'Creative testing & rotation',
                        'Audience refresh & exclusions',
                        'Weekly performance report',
                        'Slack / email access',
                        'Quarterly strategy review',
                    ],
                    'timeline' => 'Ongoing weekly retainer',
                    'idealFor' => 'Brands spending $1k–$50k / month on a single platform.',
                ],
                [
                    'slug'  => 'multi-platform-setup',
                    'name'  => 'Multi-Platform Ads Setup (Google + Meta + TikTok)',
                    'price' => 500,
                    'cycle' => 'project',
                    'blurb' => 'Three platforms launched together with consistent tracking and audiences.',
                    'detail'=> "A unified launch across Google, Meta, and TikTok. Pixel + CAPI on all three, shared UTM scheme, audience seeds wired across platforms, and one consolidated reporting view in Looker Studio.",
                    'includes' => [
                        'Google + Meta + TikTok build',
                        'Cross-platform tracking parity',
                        'Shared UTM + naming convention',
                        'Looker Studio dashboard (basic)',
                        '21-day post-launch QA',
                        'Optional 4th platform: +$150',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Brands running multi-channel paid acquisition.',
                ],
                [
                    'slug'  => 'conversion-tracking',
                    'name'  => 'Conversion Tracking & Attribution Setup',
                    'price' => 150,
                    'cycle' => 'project',
                    'blurb' => 'Server-side tracking, GA4, GTM, and clean attribution across your funnel.',
                    'detail'=> "iOS 14, third-party cookie deprecation, and ad blockers all eat your data. We rebuild your tracking with server-side events, GA4, GTM, and clean attribution so you trust what you see — and optimize off real numbers.",
                    'includes' => [
                        'GTM + GA4 implementation',
                        'Server-side conversion events',
                        'Multi-platform CAPI / S2S setup',
                        'Attribution model selection',
                        'Looker Studio reporting (basic)',
                        'Documentation handoff',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'Anyone running ads who isn\'t sure their data is right.',
                ],
                [
                    'slug'  => 'streaming-display-setup',
                    'name'  => 'Streaming / Display Ads Setup',
                    'price' => 250,
                    'cycle' => 'project',
                    'blurb' => 'Get on CTV, programmatic display, and audio with a clean launch.',
                    'detail'=> "Get your brand on streaming TV, programmatic display, and audio (Spotify / Pandora) with creative specs sorted, audiences defined, and tracking that actually fires post-impression.",
                    'includes' => [
                        'CTV / streaming setup',
                        'Programmatic display launch',
                        'Audio ad launch (optional)',
                        'Audience + geo strategy',
                        'Pixel + post-impression tracking',
                        'First-month creative recs',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Brands ready to expand beyond Google / Meta / TikTok.',
                ],
            ],
        ],

        'crm-automation' => [
            'id'      => 'crm-automation',
            'order'   => 5,
            'eyebrow' => 'Automate',
            'title'   => 'CRM & Marketing Automation',
            'tagline' => 'Pipelines that run themselves.',
            'icon'    => 'workflow',
            'hero'    => 'Set up your CRM, automate your follow-up, and turn manual work into compounding revenue while you sleep.',
            'blurb'   => 'GoHighLevel, Zoho, Zapier, and custom workflows that turn leads into customers automatically.',
            'process' => [
                ['Map',     'Audit current ops + lead flow'],
                ['Build',   'Configure CRM + automations'],
                ['Connect', 'Wire up forms, calendars, payments'],
                ['Train',   'Team training + documentation'],
            ],
            'items' => [
                [
                    'slug'  => 'ghl-full-setup',
                    'name'  => 'GoHighLevel Full Setup',
                    'price' => 500,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A complete GHL build — pipelines, workflows, calendars, and automations.',
                    'detail'=> "A turnkey GoHighLevel setup: opportunity pipelines, workflow automations, calendar booking, SMS / email sequences, and reporting dashboards. Done in your sub-account, fully documented, and ready for your team to run with from day one.",
                    'includes' => [
                        '2 sales pipelines configured',
                        '5 core automations built',
                        'Calendar + appointment booking',
                        'SMS + email sequences',
                        'Reporting dashboard',
                        'Loom training videos',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Agencies, coaches, and service businesses on GHL.',
                ],
                [
                    'slug'  => 'ghl-snapshot',
                    'name'  => 'GHL Snapshot Customization',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'Customize a GHL snapshot to your exact business and brand.',
                    'detail'=> "Take a stock GHL snapshot and turn it into something that actually fits your business — branded, your offers, your funnels, your sequences. Faster than building from scratch when a snapshot gets you 70% of the way there.",
                    'includes' => [
                        'Snapshot review + customization',
                        'Brand + copy alignment',
                        'Custom triggers + actions',
                        'Calendar + form rebuild',
                        'Pipeline alignment',
                        'Documentation handoff',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'Agencies reselling GHL or new GHL users.',
                ],
                [
                    'slug'  => 'crc-setup',
                    'name'  => 'Credit Repair Cloud Setup & Automation',
                    'price' => 450,
                    'cycle' => 'project',
                    'blurb' => 'Credit Repair Cloud configured for compliance, dispute flow, and onboarding.',
                    'detail'=> "A full CRC setup: client onboarding flow, dispute templates, automated dispute cycles, e-sign integration, and compliance-aware processes. Plug-and-play for credit repair pros.",
                    'includes' => [
                        'CRC account configuration',
                        'Client onboarding flow',
                        'Dispute letter templates',
                        'Automated dispute cycles',
                        'E-sign + payment integration',
                        'Team training',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Credit repair companies launching or scaling.',
                ],
                [
                    'slug'  => 'dispute-fox-setup',
                    'name'  => 'Dispute Fox Setup & Automation',
                    'price' => 450,
                    'cycle' => 'project',
                    'blurb' => 'Dispute Fox configured with workflows, templates, and integrations.',
                    'detail'=> "Dispute Fox setup: dispute workflows, custom letter templates, e-sign, payment processing, and CRM / marketing automation hooks. The full system, ready for your team.",
                    'includes' => [
                        'Dispute Fox configuration',
                        'Custom dispute workflows',
                        'Letter templates',
                        'E-sign + payment',
                        'CRM webhook integration',
                        'Team training',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'Credit repair pros switching to or starting on Dispute Fox.',
                ],
                [
                    'slug'  => 'zoho-setup',
                    'name'  => 'Zoho CRM Setup',
                    'price' => 400,
                    'cycle' => 'project',
                    'blurb' => 'Zoho CRM configured around your sales motion, with automations and dashboards.',
                    'detail'=> "A complete Zoho CRM setup: lead, account, contact, and deal modules customized to your sales motion, blueprint workflows, custom fields, and reporting dashboards. Trained for your team.",
                    'includes' => [
                        'Modules configured to your motion',
                        'Custom fields + layouts',
                        'Blueprint workflows',
                        'Email + task automations',
                        'Reporting dashboards',
                        'Team training',
                    ],
                    'timeline' => '7–10 business days',
                    'idealFor' => 'B2B teams running Zoho.',
                ],
                [
                    'slug'  => 'zapier-zap',
                    'name'  => 'Zapier Automation (per Zap)',
                    'price' => 50,
                    'cycle' => 'per Zap',
                    'blurb' => 'A Zap built and tested — multi-step, with branching and filters.',
                    'detail'=> "One production-ready Zap: multi-step, with filters, Paths branching, and code steps if needed. Tested with real data and documented. Volume discount on bulk orders.",
                    'includes' => [
                        '1 multi-step Zap built',
                        'Filters + Paths if needed',
                        'Code steps where required',
                        'Tested with real data',
                        'Documentation',
                        'Volume discount on bulk',
                    ],
                    'timeline' => '1–2 business days',
                    'idealFor' => 'Stitching SaaS tools together.',
                ],
                [
                    'slug'  => 'webhook-architecture',
                    'name'  => 'Webhook Architecture (custom flow)',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'A reliable webhook architecture with retries, logs, and observability.',
                    'detail'=> "Custom webhook plumbing — receive, validate, queue, retry, and log webhooks reliably. The right answer when your Zaps keep breaking and you need real engineering instead.",
                    'includes' => [
                        'Webhook receiver + validation',
                        'Queue + retry logic',
                        'Logging + observability',
                        'Error alerts',
                        'Documentation',
                        'Optional dashboard',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Teams whose Zaps keep breaking.',
                ],
                [
                    'slug'  => 'lead-management',
                    'name'  => 'Lead Management System Build',
                    'price' => 350,
                    'cycle' => 'project',
                    'blurb' => 'Round-robin routing, lead scoring, and SLA alerts on your leads.',
                    'detail'=> "A real lead management system: round-robin routing, lead scoring, SLA alerts to reps, missed-lead escalation, and full reporting. Built so leads never sit in an inbox cooling off.",
                    'includes' => [
                        'Round-robin lead routing',
                        'Lead scoring model',
                        'SLA alerts + escalations',
                        'Rep dashboards',
                        'Missed-lead workflows',
                        'Reporting setup',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Teams with multiple sales reps.',
                ],
                [
                    'slug'  => 'appointment-automation',
                    'name'  => 'Appointment & Calendar Automation',
                    'price' => 150,
                    'cycle' => 'project',
                    'blurb' => 'Calendar + booking flow with confirmations, reminders, and no-show recovery.',
                    'detail'=> "Set up your calendar (Calendly / Cal.com / GHL) with branded booking, automated confirmations, SMS / email reminders at 24h and 1h, and no-show follow-up flows. Cuts no-shows by 30–50%.",
                    'includes' => [
                        'Calendar configuration',
                        'Branded booking page',
                        'Confirmation emails + SMS',
                        '24h + 1h reminders',
                        'No-show recovery flow',
                        'Calendar sync',
                    ],
                    'timeline' => '2–3 business days',
                    'idealFor' => 'Anyone who books calls or appointments.',
                ],
                [
                    'slug'  => 'referral-system',
                    'name'  => 'Referral / Affiliate System Setup',
                    'price' => 300,
                    'cycle' => 'project',
                    'blurb' => 'A real referral or affiliate system — tracking, payouts, and a clean partner portal.',
                    'detail'=> "A full referral / affiliate program: signup flow, unique tracking links, commission rules, payout reporting, and a partner dashboard. The infrastructure to actually pay people who send you customers.",
                    'includes' => [
                        'Affiliate platform configured',
                        'Signup + onboarding flow',
                        'Unique link tracking',
                        'Commission + payout rules',
                        'Partner dashboard',
                        'Email sequences for partners',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Brands wanting a real partner channel.',
                ],
            ],
        ],

        'organic' => [
            'id'      => 'organic',
            'order'   => 6,
            'eyebrow' => 'Grow',
            'title'   => 'Organic Marketing',
            'tagline' => 'Compounding distribution.',
            'icon'    => 'megaphone',
            'hero'    => 'Social, email, SMS, and DM systems that turn attention into revenue without paying for every click.',
            'blurb'   => 'Social, email, SMS, and DM systems that compound attention into pipeline.',
            'process' => [
                ['Strategy', 'Channel mix + content angles'],
                ['Build',    'Templates, cadence, and automation'],
                ['Run',      'Production + posting + sending'],
                ['Optimize', 'Engagement + conversion review'],
            ],
            'items' => [
                [
                    'slug'  => 'social-management',
                    'name'  => 'Social Media Management (per platform / month)',
                    'price' => 300,
                    'cycle' => 'mo',
                    'tag'   => 'popular',
                    'blurb' => 'A real social channel — content, posting, and community — on one platform.',
                    'detail'=> "Per-platform monthly social management: 12+ posts produced, posting schedule, community engagement, and monthly performance reporting. Pick your channel — IG, TikTok, X, or LinkedIn.",
                    'includes' => [
                        '12+ posts / month',
                        'Posting + scheduling',
                        'Community engagement',
                        'Monthly performance report',
                        'Quarterly strategy review',
                        'Platform: IG / TikTok / X / LinkedIn',
                    ],
                    'timeline' => 'Ongoing monthly retainer',
                    'idealFor' => 'Brands serious about a single channel.',
                ],
                [
                    'slug'  => 'email-automation',
                    'name'  => 'Email Marketing Automation Setup',
                    'price' => 250,
                    'cycle' => 'project',
                    'blurb' => 'Welcome series, abandoned cart, and post-purchase flows — done right.',
                    'detail'=> "A complete email lifecycle setup: welcome series, abandoned cart, post-purchase, and win-back. Includes deliverability tuning so your emails actually hit the inbox instead of promotions or spam.",
                    'includes' => [
                        'Welcome series (4 emails)',
                        'Abandoned cart flow',
                        'Post-purchase flow',
                        'Win-back flow',
                        'Deliverability tuning',
                        'Klaviyo / Mailchimp / etc.',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Any business with a customer list.',
                ],
                [
                    'slug'  => 'sms-automation',
                    'name'  => 'SMS Marketing Automation Setup',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'TCPA-compliant SMS flows + a broadcast cadence that doesn\'t get you banned.',
                    'detail'=> "A clean SMS marketing setup: TCPA-compliant opt-in, automated flows (welcome, cart, post-purchase), and a broadcast cadence framework. The compliance work done right so you don't get your number shut down.",
                    'includes' => [
                        'TCPA-compliant opt-in',
                        'Welcome + cart flows',
                        'Post-purchase flow',
                        'Broadcast cadence framework',
                        'Number + carrier setup',
                        'Compliance documentation',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'DTC brands and high-velocity offers.',
                ],
                [
                    'slug'  => 'linkedin-dm',
                    'name'  => 'LinkedIn DM Outreach Campaign Setup',
                    'price' => 300,
                    'cycle' => 'project',
                    'blurb' => 'A real B2B outreach campaign on LinkedIn — targeting, copy, and tools.',
                    'detail'=> "A LinkedIn DM outreach campaign: ICP targeting, message sequences, profile optimization, and the tooling (Sales Navigator + automation) to run it without getting flagged. Built for B2B founders and sales teams.",
                    'includes' => [
                        'ICP + audience targeting',
                        'Profile optimization',
                        'Message sequence (3–5 steps)',
                        'Tool setup (compliance-aware)',
                        'Reply handling playbook',
                        'First 30-day support',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'B2B founders and sales teams.',
                ],
                [
                    'slug'  => 'ai-influencer',
                    'name'  => 'AI Influencer System Setup',
                    'price' => 500,
                    'cycle' => 'project',
                    'tag'   => 'new',
                    'blurb' => 'Build a virtual AI influencer with a content production system.',
                    'detail'=> "A complete AI influencer setup: persona + visual identity, content production pipeline, posting automation, and DM / comment handling. Built so you can scale a brand persona without putting a face behind it.",
                    'includes' => [
                        'Persona + visual identity',
                        'Content production pipeline',
                        'Posting automation',
                        'Cross-platform distribution',
                        'DM / comment handling',
                        'Documentation + handoff',
                    ],
                    'timeline' => '10–14 business days',
                    'idealFor' => 'Brands wanting a face-less content system.',
                ],
            ],
        ],

        'hosting' => [
            'id'      => 'hosting',
            'order'   => 7,
            'eyebrow' => 'Secure',
            'title'   => 'Hosting, Security & Infrastructure',
            'tagline' => 'Locked down. Always on.',
            'icon'    => 'shield',
            'hero'    => 'VPS, security, and infrastructure built around uptime and zero-trust security best practices.',
            'blurb'   => 'VPS provisioning, security hardening, and ongoing maintenance for sites and apps.',
            'process' => [
                ['Provision', 'VPS spin-up + hardening'],
                ['Configure', 'DNS, SSL, firewall, monitoring'],
                ['Secure',    'WAF, 2FA, RBAC, malware scans'],
                ['Maintain',  'Monthly patching + backups'],
            ],
            'items' => [
                [
                    'slug'  => 'vps-setup',
                    'name'  => 'VPS Setup & Hardening',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'A clean, hardened VPS — provisioned, secured, and ready for your apps.',
                    'detail'=> "We spin up your VPS (DigitalOcean, Linode, AWS, etc.), harden it, install your stack (LEMP / LAMP / Node), and hand over a clean, secure server. SSH keys, non-root users, and firewall configured from minute one.",
                    'includes' => [
                        'VPS provisioning',
                        'OS hardening + auto-updates',
                        'Firewall (UFW / iptables)',
                        'Stack install (LEMP / LAMP / Node)',
                        'SSH keys + non-root users',
                        'Documentation handoff',
                    ],
                    'timeline' => '2–3 business days',
                    'idealFor' => 'Anyone deploying their own apps.',
                ],
                [
                    'slug'  => 'dns-ssl',
                    'name'  => 'DNS & SSL Configuration',
                    'price' => 75,
                    'cycle' => 'project',
                    'blurb' => 'DNS records + SSL/TLS done right — including SPF, DKIM, and DMARC.',
                    'detail'=> "A clean DNS + SSL configuration: A / AAAA records, CNAMEs, MX, SPF / DKIM / DMARC for email auth, and an automated SSL with HSTS. The boring infra work done right.",
                    'includes' => [
                        'DNS records (A, MX, etc.)',
                        'SSL certificate + auto-renewal',
                        'HSTS + secure headers',
                        'SPF / DKIM / DMARC setup',
                        'Email deliverability check',
                        'Documentation handoff',
                    ],
                    'timeline' => '1–2 business days',
                    'idealFor' => 'New domains or fixing email / SSL issues.',
                ],
                [
                    'slug'  => 'security-implementation',
                    'name'  => 'Website Security Implementation',
                    'price' => 175,
                    'cycle' => 'project',
                    'blurb' => 'WAF, malware scanning, and automated backups — set and protected.',
                    'detail'=> "Lock down your site: web application firewall, malware scanner, automated daily off-site backups, and security headers configured to OWASP best practices. The standard kit every real site should ship with.",
                    'includes' => [
                        'WAF configuration',
                        'Malware scanner installed',
                        'Daily off-site backups',
                        'Security headers (CSP, HSTS, etc.)',
                        'Login hardening + bot protection',
                        'Optional uptime monitor',
                    ],
                    'timeline' => '2–3 business days',
                    'idealFor' => 'Anyone running a real site (esp. WordPress).',
                ],
                [
                    'slug'  => '2fa-rbac',
                    'name'  => '2FA + RBAC Setup',
                    'price' => 150,
                    'cycle' => 'project',
                    'blurb' => 'Two-factor auth + role-based access control on your app or admin.',
                    'detail'=> "Add real auth security: TOTP-based 2FA (or WebAuthn), role-based access control with granular permissions, and full audit logging. The minimum any multi-user app should ship.",
                    'includes' => [
                        'TOTP / WebAuthn 2FA',
                        'Role-based access control',
                        'Permission matrix + admin UI',
                        'Audit log of admin actions',
                        'Session timeout + IP rules',
                        'Documentation handoff',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'SaaS, admin dashboards, and any multi-user app.',
                ],
                [
                    'slug'  => 'api-security',
                    'name'  => 'API Security Hardening',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => 'API auth, rate limiting, schema validation, and abuse detection.',
                    'detail'=> "Lock down your API: token / JWT auth, per-key rate limiting, schema validation, abuse detection, and clear error responses. OWASP API Top 10 audited and remediated.",
                    'includes' => [
                        'Auth (JWT / OAuth / API keys)',
                        'Rate limiting per key / IP',
                        'Schema validation',
                        'Abuse + bot detection',
                        'Error response hardening',
                        'OWASP API Top 10 audit',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Any team running a public-facing API.',
                ],
                [
                    'slug'  => 'monthly-maintenance',
                    'name'  => 'Monthly Maintenance & Security Retainer',
                    'price' => 95,
                    'cycle' => 'mo',
                    'tag'   => 'popular',
                    'blurb' => 'Patching, backups, malware scans, and uptime — every single month.',
                    'detail'=> "Ongoing monthly maintenance: WordPress / dependency updates, security patching, daily backup verification, malware scans, and a monthly status report. The site insurance every business should carry.",
                    'includes' => [
                        'Monthly core + plugin updates',
                        'Daily backup verification',
                        'Weekly malware scan',
                        'Uptime monitoring',
                        'Monthly status report',
                        'Emergency response (priority)',
                    ],
                    'timeline' => 'Ongoing monthly retainer',
                    'idealFor' => 'Anyone with a live site.',
                ],
            ],
        ],

        'branding' => [
            'id'      => 'branding',
            'order'   => 8,
            'eyebrow' => 'Brand',
            'title'   => 'Branding & Creative',
            'tagline' => 'Look like the brand they trust.',
            'icon'    => 'sparkle',
            'hero'    => 'A premium brand identity, video, and creative — without paying premium-agency rates.',
            'blurb'   => 'Logos, brand kits, scripts, and creative assets that make your brand actually look the part.',
            'process' => [
                ['Discover', 'Brand goals + audience'],
                ['Design',   'Identity + assets'],
                ['Deliver',  'Files + guidelines'],
                ['Iterate',  'Optional retainer for ongoing work'],
            ],
            'items' => [
                [
                    'slug'  => 'logo-design',
                    'name'  => 'Logo Design',
                    'price' => 25,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A clean, modern logo with primary, secondary, and favicon variants.',
                    'detail'=> "A focused logo design engagement: 3 concepts, 2 rounds of revisions, final files in vector formats with primary, secondary, and favicon variants. Affordable, fast, and not generic.",
                    'includes' => [
                        '3 logo concepts',
                        '2 rounds of revisions',
                        'Vector files (SVG, AI, PDF)',
                        'PNG + JPG exports',
                        'Primary + secondary marks',
                        'Favicon + social avatar',
                    ],
                    'timeline' => '3–5 business days',
                    'idealFor' => 'Anyone needing a clean logo fast.',
                ],
                [
                    'slug'  => 'brand-kit',
                    'name'  => 'Full Brand Identity Kit',
                    'price' => 100,
                    'cycle' => 'project',
                    'tag'   => 'popular',
                    'blurb' => 'A complete brand identity — logo, colors, fonts, and a usage guide.',
                    'detail'=> "A complete brand identity package: logo system, color palette with full color codes, typography pairing, usage rules, and a one-pager guide your team can hand to any designer or printer.",
                    'includes' => [
                        'Logo system (primary + variants)',
                        'Color palette (hex / RGB / CMYK)',
                        'Typography pairing',
                        'Usage rules + spacing',
                        '1-page brand guide PDF',
                        'All source files',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Brands ready to look the part.',
                ],
                [
                    'slug'  => 'short-form-script',
                    'name'  => 'Short-Form Video Scriptwriting (per script)',
                    'price' => 30,
                    'cycle' => 'per script',
                    'blurb' => 'A short-form video script — hook, body, and CTA — built for retention.',
                    'detail'=> "One short-form video script (30–90 seconds) with a strong hook, retention beats, and a clear CTA. Optimized for TikTok, Reels, and Shorts. Built around the structures that actually keep viewers watching.",
                    'includes' => [
                        '1 short-form script',
                        'Hook + body + CTA',
                        'Retention beat structure',
                        'Optimized for short-form',
                        '1 round of revisions',
                        'Volume discount on bulk',
                    ],
                    'timeline' => '1–2 business days',
                    'idealFor' => 'Creators and brands posting short-form.',
                ],
                [
                    'slug'  => 'canva-design',
                    'name'  => 'Canva Creative Design (per asset)',
                    'price' => 35,
                    'cycle' => 'per asset',
                    'blurb' => 'A polished Canva design — editable by your team after delivery.',
                    'detail'=> "One on-brand Canva creative — social post, ad, carousel, story, or thumbnail. Delivered as an editable Canva template your team can reuse and remix without ever touching Photoshop.",
                    'includes' => [
                        '1 Canva creative',
                        'On-brand to your guide',
                        'Editable Canva template',
                        '1 round of revisions',
                        'PNG + JPG exports',
                        'Volume discount on bulk',
                    ],
                    'timeline' => '1–2 business days',
                    'idealFor' => 'Brands needing fast, on-brand creative.',
                ],
                [
                    'slug'  => 'collateral-pack',
                    'name'  => 'Digital Marketing Collateral Pack (10 assets)',
                    'price' => 200,
                    'cycle' => 'project',
                    'blurb' => '10 polished marketing assets — pitch deck, one-pagers, social, and more.',
                    'detail'=> "A 10-asset collateral pack: pitch deck slides, one-pagers, social templates, ad creatives — designed in your brand and delivered as editable files. The 'launch kit' for sales-led teams.",
                    'includes' => [
                        '10 polished assets',
                        'On-brand design system',
                        'Pitch deck / one-pager / social',
                        'Editable source files',
                        '2 rounds of revisions',
                        'PDF + PNG + Canva delivery',
                    ],
                    'timeline' => '5–7 business days',
                    'idealFor' => 'Sales-led teams that pitch often.',
                ],
            ],
        ],

    ],
];
